Refactor Workers tests
OpenSTFoundation/openst-payments pull request #62
Opened 2018-02-20 14:28 UTC by jasonklein

Refactors Workers tests. Explanations below so it's clear why I changed what I changed:
- `constructor.js`—removed, as `Workers.Workers` takes no arguments and contains no logic
- `is_worker.js`—removed, as the testing of `setWorker` otherwise sufficiently covers `isWorker`, but moved expiration testing into `set_worker.js`
- `remove.js`—stripped away:
  - confirmation that address has code (I understand that the point was to show the change from w/code to without)
    - confirmed by successfully setting ops/admin and the access control test
    - this is testing EVM/Solidity
  - use of `setWorker`/`isWorker` are not necessary (calling a function is not necessarily a useful way to confirm self-destruction)
  - calls to contract after confirming address holds no code
    - `false` does not prove that the workers are no longer valid
    - this is testing EVM/Solidity

2018-02-21 16:21 UTC, benjaminbollen requested changes
LGTM. - should the test be corrected?

2018-02-22 06:39 UTC, jasonklein commented on test/contracts/workers/remove.js
> +    // call remove from admin address
As discussed: the `beforeEach` redeploys.

2018-02-22 07:36 UTC, benjaminbollen commented on test/contracts/workers/remove.js
> +    // call remove from admin address
understood! thanks!

2018-02-22 07:36 UTC, benjaminbollen approved these changes

2018-02-22 09:17 UTC, merged